trigger:
- master

pool:

  vmImage: "vs2017-win2016"

variables:
- name: variable
  value: False 

steps:  


- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      # Write your PowerShell commands here.
      $editedFiles = git diff HEAD HEAD~ --name-only
      $editedFiles | ForEach-Object {
    Switch -Wildcard ($_ ) {
        'SubFolderA/*' { Write-Output "##vso[task.setvariable variable=variable]True" }}
  
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      # Write your PowerShell commands here.
      
      Write-Host "Hello World"

- task: UiPathInstallPlatform-preview@2

 

- task: UiPathTest@2
  inputs:
    testTarget: 'TestProject'
    orchestratorConnection: 'Orchestrator'
    testProjectPath: 'project.json'
    folderName: 'UiBank_Demo'
    testReportDestination: '$(Build.ArtifactStagingDirectory)\Output\result.xml'