trigger:
- master

pool:

  vmImage: "vs2017-win2016"

- task: UiPathInstallPlatform-preview@2

- task: UiPathTest@2
  inputs:
    testTarget: 'TestProject'
    orchestratorConnection: 'Orchestrator'
    testProjectPath: 'project.json'
    folderName: 'UiBank_Demo'
    testReportDestination: '$(Build.ArtifactStagingDirectory)\Output\result.xml'



