trigger:
- master

pool:

  vmImage: "vs2017-win2016"

steps:

- task: UiPathInstallPlatform@2

#- task: UiPathPack@2
#  inputs:
#    versionType: 'AutoVersion'
#    projectJsonPath: 'project.json'
#    outputType: 'Tests'
#    orchestratorConnection: 'staging.uipath.com'
#    outputPath: '$(Build.ArtifactStagingDirectory)\Output'
#    traceLevel: 'Verbose'

    
#- task: UiPathDeploy@2
#  inputs:
#    orchestratorConnection: 'staging.uipath.com'
#    packagesPath: '$(Build.ArtifactStagingDirectory)\Output'
#    folderName: 'Tenant'
#    entryPoints: 'Main.xaml'
#    traceLevel: 'Verbose'

- task: UiPathTest@2
  inputs:
    testTarget: 'TestProject'
    orchestratorConnection: 'staging.uipath.com'
    testProjectPath: 'project.json'
    folderName: 'Modern Folder'
    testReportDestination: 'Output'