trigger:
- master

pool:

  vmImage: "vs2017-win2016"

steps:

- task: UiPathInstallPlatform@2

- task: UiPathPack@2
  inputs:
    versionType: 'AutoVersion'
    projectJsonPath: 'project.json'
    outputType: 'Tests'
    orchestratorConnection: 'cloud.uipath.com'
    outputPath: '$(Build.ArtifactStagingDirectory)\Output'
    traceLevel: 'Verbose'

    
- task: UiPathDeploy@2
  inputs:
    orchestratorConnection: 'cloud.uipath.com'
    packagesPath: '$(Build.ArtifactStagingDirectory)\Output'
    folderName: 'Modern Folder'
    entryPoints: 'Main.xaml'
    traceLevel: 'Verbose'

