trigger:
- master
- releases/*

pool:

  vmImage: "vs2017-win2016"

steps:
- task: UiPathInstallPlatform-preview@2

- task: UiPathTest@2
  inputs:
    testTarget: 'TestSet'
    orchestratorConnection: 'DemoOrchestrator'
    testSet: 'UiBank_Demo'
    folderName: 'ThomasStocker_modern_folder'
    testReportDestination: 'output'